function y = highfilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 29-Mar-2018 16:55:53

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.4;  % Stopband Frequency
    Fpass = 0.5;  % Passband Frequency
    Astop = 80;   % Stopband Attenuation (dB)
    Apass = 10;   % Passband Ripple (dB)
    Fs    = 120;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


