function y = gammafilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 23-Mar-2018 13:03:52

persistent Hd;

if isempty(Hd)
    
    Fstop = 31;   % Stopband Frequency
    Fpass = 32;   % Passband Frequency
    Astop = 60;   % Stopband Attenuation (dB)
    Apass = 1;    % Passband Ripple (dB)
    Fs    = 120;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

